"""Render the quality bench (quality-bench.py) results as one markdown page.

  python qwen38-tuning\\tools\\quality-report.py > docs\\results\\11-quality-bench-2026-09-05.md

Everything here is read from the cells' summary.json, requests.jsonl and
server-timing-lines.txt; nothing is typed in by hand.
"""
import glob, json, os, re

RESULTS = r"C:\AI\qwen38-tuning\results\quality-2026-09-05"
LABEL = {"A": "EXL3 SC 4.0bpw H5 @ 262,144", "B": "EXL3 3.5bpw @ 262,144", "C": "llama.cpp NVFP4-LOW @ 200,704"}


def load():
    cells = []
    for sd in sorted(glob.glob(os.path.join(RESULTS, "*-r*"))):
        if "-superseded-" in sd or sd.endswith("-stuck"):
            continue
        sj = os.path.join(sd, "summary.json")
        if os.path.exists(sj):
            s = json.load(open(sj, encoding="utf-8")); s["_dir"] = sd; cells.append(s)
    return cells


def timing_rows(s):
    """Per-task prefill/decode from the server's own print_timing lines."""
    rows, cur = [], {}
    for line in open(os.path.join(s["_dir"], "server-timing-lines.txt"), encoding="utf-8", errors="replace"):
        m = re.search(r"task (\d+) \| prompt eval time = +([\d.]+) ms / +(\d+) tokens.*?([\d.]+) tokens per second\)?\s*(?:\[(\d+) cached\])?", line)
        if m:
            cur = dict(task=int(m.group(1)), pp_ms=float(m.group(2)), pp_tokens=int(m.group(3)), pp_tps=float(m.group(4)), cached=int(m.group(5) or 0)); continue
        m = re.search(r"task (\d+) \| +eval time = +([\d.]+) ms / +(\d+) tokens.*?([\d.]+) tokens per second", line)
        if m and cur.get("task") == int(m.group(1)):
            cur.update(tg_ms=float(m.group(2)), tg_tokens=int(m.group(3)), tg_tps=float(m.group(4))); rows.append(cur); cur = {}
    return rows


def cell_rows(s):
    """The server log holds the whole boot, so keep only the tasks that belong to
    this cell: on EXL3 match generated-token counts against the cell's own
    request log (consumed in order); on llama the boot was the cell's alone."""
    rows = timing_rows(s)
    rq = os.path.join(s["_dir"], "requests.jsonl")
    if not os.path.exists(rq):
        return rows
    wanted = [json.loads(l).get("output_tokens") for l in open(rq, encoding="utf-8") if l.strip()]
    wanted = [w for w in wanted if w]
    kept, i = [], 0
    for r in rows:
        if i < len(wanted) and r["tg_tokens"] == wanted[i]:
            kept.append(r); i += 1
    return kept


def main():
    cells = load()
    out = []
    out.append("# 11 — Three-artifact quality bench through Claude Code (2026-09-05)\n")
    out.append("Generated by `qwen38-tuning/tools/quality-report.py` from `qwen38-tuning/results/quality-2026-09-05/`. One Thai brief, the one the developer used on 2026-09-03/04: *\"สร้าง Landing Page แนะนำ Google โดยใช้ Editorial Minimalism × Modern Swiss × Liquid Glass × Visible Grid | ทำเป็น HTML ไฟล์เดียว\"*. `noskill` = a fresh `CLAUDE_CONFIG_DIR` with no user skills; `skill` = the developer's own `~/.claude` (324 skills) and the brief as typed (`/using-design /ask-xeno`) plus `จบด้วย /design-ship-gate`. Afternoon arms (the developer's question, which *kind* of skill moves the model): `gateonly` = only `design-ship-gate`, `designonly` = the design suite + `ask-xeno`, `both` = the two together — each in its own isolated `CLAUDE_CONFIG_DIR`, 4.0bpw only, three reps. The gate score is computed by the runner, not by the model. **One sample per cell in the morning; three per afternoon arm — still a ranking, not a rate.** Effort: `--effort medium` on EXL3; llama-server ignores it and runs the template default xhigh.\n")
    out.append("## Cells\n")
    out.append("| cell | artifact | arm | gate | wall | turns | API calls | output tok | thinking chars | page | fonts | OG | dark | Thai chars |")
    out.append("|---|---|---|---|---:|---:|---:|---:|---:|---|---|---|---|---:|")
    for s in cells:
        g = s.get("gate") or {}
        out.append(f"| {s['cell']}-{s['arm']}-r{s['rep']} | {LABEL[s['cell']]} | {s['arm']} | **{g.get('score','-')}** | {s.get('wall_s',0)/60:.1f} min | {s.get('num_turns','-')} | {s.get('api_calls','-')} | {s.get('output_tokens','-')} | {s.get('thinking_chars','-')} | {s.get('page_lines','-')} lines / {round((s.get('page_bytes') or 0)/1024)} KB | {len(g.get('fonts') or [])}: {', '.join(g.get('fonts') or [])} | {len(g.get('og') or [])}/3 | {'yes' if g.get('dark_matches') else 'no'} | {g.get('thai_chars','-')} |")
    out.append("\nGate columns not shown because every cell passed them: invisible stats in dark mode 0, overflow at 390 px 0, text colliding with the `h1` 0, no descendant-`span` rule on numeric blocks. Tracking candidates (values tighter than −0.025em, to be judged by size): " + ", ".join(f"{s['cell']}-{s['arm']} {((s.get('gate') or {}).get('tracking_candidates'))}" for s in cells) + ".\n")
    # per-arm summary over reps (the afternoon question)
    from collections import defaultdict
    groups = defaultdict(list)
    for s_ in cells:
        if s_.get("task", "page") == "page" and s_["cell"] == "A":
            groups[s_["arm"]].append(s_)
    if any(len(v) > 1 for v in groups.values()):
        out.append("## Which kind of skill moves the model — 4.0bpw, medium, per arm over reps\n")
        out.append("| arm | skills in the session | reps | gate (each rep) | mean wall | mean output tokens | OG present | dark present | ≤2 fonts |")
        out.append("|---|---|---:|---|---:|---:|---|---|---|")
        desc = {"noskill": "none (fresh CLAUDE_CONFIG_DIR)", "gateonly": "design-ship-gate only", "designonly": "design suite + ask-xeno", "both": "design suite + ask-xeno + design-ship-gate", "skill": "the developer's whole ~/.claude"}
        for arm in ("noskill", "gateonly", "designonly", "both", "skill"):
            v = groups.get(arm)
            if not v:
                continue
            gates = [(x.get("gate") or {}).get("score", "-") for x in v]
            og = sum(1 for x in v if len((x.get("gate") or {}).get("og") or []) == 3)
            dk = sum(1 for x in v if (x.get("gate") or {}).get("dark_matches"))
            fo = sum(1 for x in v if len((x.get("gate") or {}).get("fonts") or []) <= 2)
            out.append(f"| {arm} | {desc[arm]} | {len(v)} | {' · '.join(gates)} | {sum(x.get('wall_s', 0) for x in v) / len(v) / 60:.1f} min | {sum((x.get('output_tokens') or 0) for x in v) / len(v):,.0f} | {og}/{len(v)} | {dk}/{len(v)} | {fo}/{len(v)} |")
        out.append("\nThe gate score is the runner's eight checks. `both` rep 1 hit the 75-minute cap on a tone-mark repetition loop after its page was finished (see the incidents below); its page and gate are what existed at the cap.\n")
    # the qwen38 family's own pairs (xeno-skills #356 code-gate, #357 think): task cells
    tasks = [c for c in cells if c.get("task", "page") != "page"]
    if tasks:
        out.append("## The `qwen38` family's pairs — code and think tasks (xeno-skills #356, #357)\n")
        out.append("Fixtures in `qwen38-tuning/fixtures/`; the gate is computed by the runner. Arms: `noskill` = no skills; `codegate` / `think` = that one skill alone; `family` = `using-qwen38` + `qwen38-think` + `qwen38-code-gate` + `karpathy-guidelines`. Every cell of this batch also carried the tuning repo's `CLAUDE.md` (see the incidents).\n")
        out.append("| cell | task | arm | gate | detail | turns | turns before first edit | wall | output tok |")
        out.append("|---|---|---|---|---|---:|---:|---:|---:|")
        for c in tasks:
            g = c.get("gate") or {}
            if c["task"].startswith("code"):
                detail = f"hidden {g.get('hidden_passed')}/{g.get('hidden_passed', 0) + g.get('hidden_failed', 0)} · scope {'ok' if g.get('scope_ok') else 'NO'} · test runs seen {g.get('test_runs_seen')} · red→green {'yes' if g.get('red_then_green') else 'no'}"
            else:
                detail = f"{g.get('flaw')} · pushback {'yes' if g.get('pushback') else 'NO'} · invented {g.get('invented') or 'none'} · asked a question {'YES' if g.get('asked_question') else 'no'} · THINK line {'yes' if g.get('think_line') else 'no'}"
            out.append(f"| {c['cell']}-{c['task']}-{c['arm']}-r{c['rep']} | {c['task']} | {c['arm']} | **{g.get('score', '-')}** | {detail} | {c.get('num_turns', '-')} | {g.get('turns_before_edit', '-')} | {c.get('wall_s', 0) / 60:.1f} min | {c.get('output_tokens', '-')} |")
        out.append("")
    out.append("## Time per task (server-side, from `print_timing`)\n")
    for s in cells:
        rows = cell_rows(s)
        out.append(f"### {s['cell']}-{s['arm']}-r{s['rep']} — {LABEL[s['cell']]} ({s['arm']}), wall {s.get('wall_s',0)/60:.1f} min\n")
        out.append("| task | prompt tokens (cached) | prefill | prefill tok/s | generated | decode | decode tok/s | task total |")
        out.append("|---:|---:|---:|---:|---:|---:|---:|---:|")
        for r in rows:
            out.append(f"| {r['task']} | {r['pp_tokens']:,} ({r['cached']:,}) | {r['pp_ms']/1000:.1f} s | {r['pp_tps']:.0f} | {r['tg_tokens']:,} | {r['tg_ms']/1000:.1f} s | {r['tg_tps']:.1f} | {(r['pp_ms']+r['tg_ms'])/1000:.1f} s |")
        if rows:
            tg = sum(r["tg_tokens"] for r in rows); tt = sum(r["tg_ms"] for r in rows) / 1000; pp = sum(r["pp_ms"] for r in rows) / 1000
            out.append(f"\nSum: prefill {pp:.0f} s, decode {tt:.0f} s for {tg:,} generated tokens ({tg/tt if tt else 0:.1f} tok/s over the run); wall {s.get('wall_s',0):.0f} s, so {max(0, s.get('wall_s',0) - pp - tt):.0f} s was client-side (Claude Code thinking about tools, skills reading, gate commands, model switching queue).\n")
        rq = os.path.join(s["_dir"], "requests.jsonl")
        if os.path.exists(rq):
            reqs = [json.loads(l) for l in open(rq, encoding="utf-8") if l.strip()]
            if reqs:
                out.append("Per-request wall from the server's request log (`exl3-requests.jsonl`), in order: " + ", ".join(f"{r.get('wall_ms',0)/1000:.0f} s ({r.get('prompt_tokens')}→{r.get('output_tokens')})" for r in reqs) + ".\n")
    judgment = os.path.join(RESULTS, "judgment.md")
    if os.path.exists(judgment):
        out.append(open(judgment, encoding="utf-8").read().rstrip() + "\n")
    out.append("## What happened to the runs that are not in the table\n")
    out.append("- **B-noskill first attempt (09:34–10:49, timed out at 75 min, no page).** The runner's stop step deleted `exl3-stop.flag` three seconds after the kill, before the relaunch loop had read it, so the loop relaunched the *default* 4.0bpw model on top of the 3.5bpw boot every ~4 minutes (ten logs `exl3-serve-20260905-0932..1043`, each a full load ending in a bind error on :8000). With both cards within 0.6 GB of full the 3.5bpw server decoded at **9–10 tok/s** (prefill 110 tok/s) and after 10:21 printed `Synchronization timeout in kernel: pg_all_reduce_cpu_kernel` ×144 without a child dying — a *slow-but-alive* mode the watchdog does not catch. The rerun at 10:58, alone on the cards (7.7 / 10.9 GB), decoded at **62.7 tok/s** with zero timeouts. Same artifact, same recipe, same boot script: the only difference was VRAM headroom. This is the first same-day pair for issue #63's hypothesis A.")
    out.append("- **A-noskill's wall (6.5 min) carries ~4 min of waiting.** Its first request queued behind an orphaned request from a queue launch that was aborted at 09:24 (the server was still generating for the dead client); the server-side work of the cell is 15 s prefill + 144 s decode. Read 2.6 min, not 6.5, when comparing with B.")
    out.append("- **C-noskill first attempt (10:49–10:52).** llama-server booted while that stray EXL3 relaunch was loading; its first slot stalled at 710 of 788 prompt tokens and never produced a token (`C-noskill-r1-stuck/`). Restarted alone; the rerun is the C row above.")
    out.append("- **A-both-r1 (afternoon, 13:04–14:19, timed out at 75 min).** After writing the page and passing its own gate, the model started its Thai report and fell into a **repetition loop on the tone mark `่` (U+0E48)**: one API call produced a 127,682-character text message (`ทุ้่่่่ง 8 ข้อผ่านแล้้่่่่…`), 127,996 output tokens in 46 min at `reasoning effort = medium` — not thinking (that turn's thinking was ~80K chars, normal), not xhigh. The server's own line says what it was: draft acceptance **0.998** (95,958 of 96,111 draft tokens accepted), the drafter predicting a token that never changes. `CLAUDE_CODE_MAX_OUTPUT_TOKENS` = the whole window (the developer's 2026-09-04 setting) is what let it run: when it stopped, Claude Code compacted and re-prefilled 207,535 tokens (494 s). Second Thai-quality failure mode of the day, on the 4.0bpw H5 file this time (3.5bpw misspells; NVFP4-LOW showed neither). Once in ~40 Thai requests today; frequency unknown. A server-side loop guard is the fix that keeps the window cap (tuning-repo issue opened).")
    out.append("- **Every cell of the day carried the tuning repo's CLAUDE.md.** The work directories sat under `C:\\AI\\qwen38-tuning\\results\\…`, and Claude Code reads every ancestor `CLAUDE.md`; a `noskill` answer at 16:14 quoted the repo's *\"no verdict before evidence\"*. So `noskill` means *no skills*, not *no instructions* — the confound is the same in every arm, which leaves the arm comparison intact but makes the absolute `noskill` numbers those of a model already told to be careful and to answer in Thai. Cells run after 16:20 work in `D:\\qbench-work` (no `CLAUDE.md` in any ancestor).")
    out.append("- Fixes shipped for both: the runner no longer deletes the stop flag; `serve-exl3.cmd` refuses to relaunch when :8000 already answers and counts a death within 420 s (a model load is 2–4 min) toward the give-up guard. `bench/tests/test_exl3_watchdog.py` pins both.\n")
    out.append("## Evidence per cell\n")
    out.append("`<cell>/page.html` (the page), `stream.jsonl` (the whole Claude Code stream), `summary.json`, `requests.jsonl` (EXL3), `server-timing-lines.txt`, `desktop-light.png` / `desktop-dark.png` / `mobile.png`, `stderr.txt`, `work/` (the model's working directory as it left it).\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
